# Generated by Django 3.2.25 on 2025-02-05 01:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZillowListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zillow_id', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
                ('area_unit', models.CharField(choices=[('SqFt', 'Square Feet')], help_text='The unit of area measurement. ex. sqft', max_length=32, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(choices=[('SingleFamily', 'Single Family'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Multi-Family (2 to 4 Units)'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Other', 'Other')], default='Other', max_length=64)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('tax_value', models.IntegerField(blank=True, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_amount', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('zestimate_amount', models.IntegerField(blank=True, null=True)),
                ('zestimate_last_updated', models.DateField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
