# Generated by Django 2.1.7 on 2025-02-04 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_id', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
                ('area_unit', models.CharField(max_length=255)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('home_size', models.IntegerField(blank=True, null=True)),
                ('home_type', models.CharField(max_length=100)),
                ('last_sold_date', models.DateField(blank=True, null=True)),
                ('last_sold_price', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('property_size', models.IntegerField(blank=True, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_amount', models.IntegerField(blank=True, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, null=True)),
                ('tax_value', models.IntegerField(blank=True, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('zestimate_amount', models.IntegerField(blank=True, null=True)),
                ('zestimate_last_updated', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
