# Generated by Django 3.2.25 on 2025-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='address',
            new_name='street',
        ),
        migrations.AlterField(
            model_name='house',
            name='area_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet')], help_text='The unit of area measurement. ex. sqft', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='home_type',
            field=models.CharField(choices=[('SingleFamily', 'Single Family'), ('VacantResidentialLand', 'Vacant Residential Land'), ('Miscellaneous', 'Miscellaneous'), ('MultiFamily2To4', 'Multi-Family (2 to 4 Units)'), ('Condominium', 'Condominium'), ('Apartment', 'Apartment'), ('Duplex', 'Duplex'), ('Other', 'Other')], default='Other', max_length=64),
        ),
        migrations.AlterField(
            model_name='house',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
