# Generated by Django 3.2.25 on 2025-02-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0002_auto_20250204_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
