# Generated by Django 2.1.7 on 2019-02-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0002_auto_20190226_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='estimation_last_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='last_sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_estimation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
