# Generated by Django 3.2.25 on 2025-02-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0003_alter_house_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='ZillowListing',
        ),
    ]
