# Generated by Django 2.1.7 on 2019-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0003_auto_20190226_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='last_sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='rent_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
