# Generated by Django 3.2.25 on 2025-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0004_rename_house_zillowlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zillowlisting',
            name='area_unit',
            field=models.CharField(choices=[('SqFt', 'Square Feet')], help_text='The unit of area measurement. ex. sqft', max_length=32, null=True),
        ),
    ]
