# Generated by Django 2.1.7 on 2019-02-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0004_auto_20190226_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='estimation_last_update',
            new_name='rentzestimate_last_updated',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='rent_estimation_date',
            new_name='zestimate_last_updated',
        ),
        migrations.RemoveField(
            model_name='house',
            name='estimate_amount',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rent_estimation_amount',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='house',
            name='rentzestimate_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='zestimate_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='tax_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='tax_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_build',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='zillow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
