# Generated by Django 2.1.7 on 2019-02-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0006_auto_20190227_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='house',
            name='city',
        ),
        migrations.RemoveField(
            model_name='house',
            name='home_size',
        ),
        migrations.RemoveField(
            model_name='house',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='last_sold_price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='link',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='property_size',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='rentzestimate_amount',
        ),
        migrations.RemoveField(
            model_name='house',
            name='state',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tax_value',
        ),
        migrations.RemoveField(
            model_name='house',
            name='tax_year',
        ),
        migrations.RemoveField(
            model_name='house',
            name='year_build',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zestimate_amount',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zillow_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='zipcode',
        ),
    ]
